#set a mongodb and mongo-express container
version: "3"

networks:
  scanworks:
    driver: bridge
    external: true

services:
  pyapp:
    build: ./Pyapp
    networks:
      - scanworks
    volumes:
      - ./sharedvolume:/app/pyapp
