#set a mongodb and mongo-express container
version: "3"

networks:
  scanworks:
    driver: bridge
    external: true

services:
  pyapp:
    build: ./Pyapp
    networks:
      - scanworks
    depends_on:
      - mongodb
    volumes:
      - sharedvolume:/app

volumes:
  sharedvolume:
    driver: local
