version: "3"

networks:
  scanworks:
    driver: bridge
    external: true

services:

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./Pyapp/sqlitebrowser:/config
    ports:
      - 3000:3000
    restart: unless-stopped

    
  pyapp:
    build: ./Pyapp
    networks:
      - scanworks
    volumes:
      - ./Pyapp:/app



